---
  - name: Start server <1/3> Setup environment
    blockinfile: |
      dest=/etc/environment
      content='{{ bashrc_env_var }}'
    tags: bashrc

  - name: Start server <2/3> Start process with pm2
    become: yes
    become_user: ubuntu
    shell: chdir=/home/ubuntu/{{ application_name }} {{ pm2_start_var }} sudo pm2 start {{app_js}} --name "app"
    register: pm2start
    ignore_errors: True

  - name: Start server <3/3> Print pm2 status
    debug: var=pm2start.stdout_lines

  - name: Start server <3/3> Print pm2 error
    debug: var=pm2start.stderr
    when: "'ERROR' in pm2start.stderr"
