#!/bin/bash
source ~/.bashrc
source ~/.bash_profile
TASK="$1"
if [[ $1 == "aws" ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@../devops-vars.yml" devops-core/aws.yml
elif [[ $1 == "aws-fetch-inventories" ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@../devops-vars.yml" devops-core/aws-fetch-inventories.yml
elif [[ $1 == "aws-check-exists" ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@../devops-vars.yml" devops-core/aws-check-exists.yml
elif [[ $1 == "aws-terminate" ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@../devops-vars.yml" devops-core/aws-terminate.yml
elif [[ $1 == "install" ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@../devops-vars.yml" devops-core/install.yml
elif [[ $1 == "godaddy" ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@../devops-vars.yml" devops-core/godaddy.yml
elif [[ $1 == "deploy" && $2 != '' ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@../devops-vars.yml" devops-core/deploy.yml -l ${@:2}
elif [[ $1 == "deploy" && $2 == '' ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@../devops-vars.yml" devops-core/deploy.yml
else
  ansible-playbook -i devops-hosts --extra-vars="@../devops-vars.yml" devops-core/run-all.yml
fi
