#!/bin/bash

TASK="$1"
if [[ $1 == "aws" ]]
then
  source ~/.bashrc
  source ~/.bash_profile
  ansible-playbook -i devops-hosts --extra-vars="@devops-vars.yml" devops-core/aws.yml
elif [[ $1 == "install" ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@devops-vars.yml" devops-core/install.yml
elif [[ $1 == "godaddy" ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@devops-vars.yml" devops-core/godaddy.yml
elif [[ $1 == "webhook" ]]
then
  ansible-playbook -i devops-hosts --extra-vars="@devops-vars.yml" devops-core/webhook.yml
else
  source ~/.bashrc
  source ~/.bash_profile
  ansible-playbook -i devops-hosts --extra-vars="@devops-vars.yml" devops-core/aws.yml
  ansible-playbook -i devops-hosts --extra-vars="@devops-vars.yml" devops-core/install.yml
  ansible-playbook -i devops-hosts --extra-vars="@devops-vars.yml" devops-core/godaddy.yml
  ansible-playbook -i devops-hosts --extra-vars="@devops-vars.yml" devops-core/webhook.yml
fi
