---
  - name: Create directory under /home/ubuntu for fundity
    file: path=/home/ubuntu/fundity state=directory mode=755

 # - name: Git checkout from github
 #   git: repo=https://github.com/tomoconnor/shiny-octo-computing-machine.git
 #        dest=/srv/thingy

  - name: Copy post-receive web hook
    copy: src=thingy.super.conf dest=/etc/supervisor/conf.d/thingy.conf

  - name: Drop reverse proxy config for nginx
    copy: src=fundity.nginx.conf dest=/etc/nginx/sites-enabled/fundity.conf
    notify: restart nginx
