---
  - name: Create directory under /home/ubuntu for evalend
    file: path=/home/ubuntu/evalend-blog state=directory mode=755

  - name: ensure repository directories exists
    action: file path=/home/ubuntu/repos/evalend-blog owner=ubuntu group=ubuntu mode=0775 state=directory

  - name: create repositories
    action: command chdir=/home/ubuntu/repos/evalend-blog creates=/home/ubuntu/repos/evalend-blog/HEAD git init --bare

  - name: Copy post-receive web hook
    copy: src=post-receive dest=/home/ubuntu/repos/evalend-blog/hooks/post-receive

  - name: Drop reverse proxy config for nginx
    copy: src=evalend-blog.nginx.conf dest=/etc/nginx/sites-enabled/evalend-blog.conf
    notify: restart nginx
