---
  - name: <1/5> Create autodeploy directory under /home/ubuntu for {{ application_name }}
    file: path=/home/ubuntu/autodeploy state=directory mode=755

  - name: <2/5> Create the GitAutoDeploy file
    template: src=GitAutoDeploy.py
              dest=/home/ubuntu/autodeploy
              backup=yes
              mode=u+x

  - name: <3/5> Create the GitAutoDeploy config file
    template: src=GitAutoDeploy.conf.json
              dest=/home/ubuntu/autodeploy
              backup=yes
              mode=u+x

  - name: <4/5> Start GitAutoDeploy with pm2
    sudo: yes
    sudo_user: ubuntu
    shell: chdir=/home/ubuntu/autodeploy pm2 start GitAutoDeploy.py --name "GitAutoDeploy"
    register: pm2status

  - name: <5/5> Print PM2 status
    debug: var=pm2status.stdout_lines
