---
  - name: <1/6> Install pip package from apt
    apt: name={{ item }} state=present
    with_items:
    - python-pip

  - name: <2/6> Install pyGoDaddy from github
    become: yes
    become_user: ubuntu
    action: shell pip install git+git://github.com/claneys/pygodaddy.git

  - name: <3/6> Create the godaddy.py file
    template: src=godaddy.py
              dest=/home/ubuntu/
              backup=yes
              mode=u+x

  - name: <4/6> Execute godaddy.py
    become: yes
    become_user: ubuntu
    action: shell python /home/ubuntu/godaddy.py {{ godaddy_username }} {{ godaddy_password }}
    register: godaddy
    ignore_errors: True

  - name: <5/6> Print result
    debug: msg="success = {{ godaddy.stdout!="" }}, site = {{ nginx_server_name }}"

  - name: <6/6> Delete godaddy.py
    file: path=/home/ubuntu/godaddy.py state=absent
