---
- name: Make sure nodejs is present
  apt: pkg=nodejs state=present

- name: Make sure nodejs-legacy is present
  apt: pkg=nodejs-legacy state=present

- name: Make sure npm is present
  apt: name=npm state=present

- name: Install packages
  npm:
    name: pm2
    global: yes
    version: "{{ pm2_version | default(omit) }}"
  notify: restart pm2

- name: installing startup script
  command: >
    pm2 startup {{ pm2_startup }}
