---

- name: Install packages
  npm:
    name: pm2
    global: yes
    version: "{{ pm2_version | default(omit) }}"
  notify: restart pm2

- name: installing startup script
  command: >
    pm2 startup {{ pm2_startup }}
