---

- name: Deleting all apps
  command: >
    pm2 delete all
  ignore_errors: yes
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: Starting apps
  command: >
    pm2 start {{ item }}
  with_items: pm2_apps
