#!/bin/sh

now="$(date +'%d/%m/%Y/%r')"
echo $now

GIT_WORK_TREE=//home/ubuntu/evalend-blog git checkout -f

cd /home/ubuntu/evalend-blog
# npm install --production

# restart pm2
# /usr/local/bin/pm2 kill
# NODE_ENV=production /usr/local/bin/pm2 start /home/ubuntu/evalend-blog/index.js
# /usr/local/bin/pm2 reload index.js