---

# Install MySQL
- name: Install Mysql package
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
   - python-dev
   - libmysqlclient-dev
   - mysql-server
   - libapache2-mod-auth-mysql
   - python-mysqldb
  tags:
    - mysql

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql
  tags:
    - mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=true
  tags:
    - mysql

- name: Create Mysql Database
  mysql_db: name={{ vm_dependencies.mysql.db_name }} state=present
  tags:
    - mysql

- name: Create Mysql DB User
  mysql_user: name={{ vm_dependencies.mysql.db_user }} password={{ vm_dependencies.mysql.db_password }} priv=*.*:ALL host='%' state=present
  tags:
    - mysql