---

- name: Make sure apt-transport-https is installed
  apt:
    pkg: "apt-transport-https"
    state: installed

- name: Add Docker repository key
  apt_key:
    id: "36A1D7869245C8950F966E92D8576A8BA88D21E9"
    keyserver: "hkp://keyserver.ubuntu.com:80"
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb http://get.docker.io/ubuntu docker main"
    update_cache: yes
    state: present

- name: Install lxc-docker
  apt:
    pkg: "lxc-docker"
    state: installed
- name: Install pip
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - python-dev
    - python-pip

- name: Install Docker-py
  pip:
    name: docker-py
- name: Make sure docker is running
  service:
    name: docker
    state: started
- name: Ensure docker-compose is installed and available
  shell: sudo curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
- name: chmod docker-compose
  shell: sudo chmod +x /usr/local/bin/docker-compose
