---
- name: Install dependencies
  sudo: yes
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
  tags: nvm

- name: Install nvm
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm_version }}
  tags: nvm

- name: Source nvm in ~/.profile
  lineinfile: >
    dest=~/.profile
    line="{{ item }}"
    create=yes
  with_items:
    - source ~/.nvm/nvm.sh
    - export TEST=bah
  tags: nvm

- name: Install {{ nodejs_version }}
  command: sudo -iu {{ nvm_user }} nvm install {{ nodejs_version }}
  register: nvm_install_result
  tags: nvm

- name: Use {{ nodejs_version }}
  command: sudo -iu {{ nvm_user }} nvm alias default {{ nodejs_version }}
  register: nvm_use_result
  tags: nvm

- debug: msg="{{ nvm_use_result.stdout }}"
