---
  - name: Install nodejs
    apt: pkg=nodejs state=installed
  - name: Install node-dev
    apt: pkg=nodejs-dev state=installed
  - name: Install nodejs-legacy
    apt: pkg=nodejs-legacy state=installed
  - name: Install npm
    apt: pkg=npm state=latest
  - name: Update npm
    shell: sudo npm install -g npm
    become: ubuntu
    become_user: yes
...
